"" === VUNDLE PLUGIN MANAGER ===

set nocompatible " be iMproved 
filetype off " required! 
set rtp+=~/.vim/bundle/vundle/ 
call vundle#rc() 
" let Vundle manage Vundle 
" required!  
Bundle 'gmarik/vundle' 

" My Bundles here:  " 
" original repos on github 
Bundle 'Lokaltog/vim-powerline.git' 
Bundle 'ervandew/supertab.git'

Bundle 'tpope/vim-fugitive.git'
Bundle 'tomasr/molokai'
Bundle 'sjbach/lusty.git'
Bundle 'fholgado/minibufexpl.vim.git'
Bundle 'scrooloose/nerdtree.git'
Bundle 'Lokaltog/vim-easymotion.git'
Bundle 'git://git.wincent.com/command-t.git'


" non github repos 
Bundle 'git://git.wincent.com/command-t.git' 
" ... 

filetype plugin indent on " required!
"" -------------------
colorscheme molokai

syntax on

" Numbers
set number
set numberwidth=4

set showbreak=...
set noeb vb t_vb=



"" remap to maintain line selected after ident
vnoremap > >gv
vnoremap < <gv

"" map to ident/unident
nnoremap <Tab> >>_
nnoremap <S-Tab> <<_
inoremap <S-Tab> <C-D>
vnoremap <Tab> >gv
vnoremap <S-Tab> <gv

nmap , :

"" Tagbar switcher
nmap <F8> :TagbarToggle<CR>

""get the File, Open dialog box to default to the current file's directory
set browsedir=buffer

"" Status bar
set laststatus=2
set statusline=(%n)\ %F\ [%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%m%r%y%=%c,%l/%L\ %P 
set statusline+=%{fugitive#statusline()}

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set expandtab
set smarttab      " insert tabs on the start of a line  according to   shiftwidth, not tabstop

set autoindent    " always set autoindenting on
set copyindent    " copy the previous indentation on autoindenting

set hidden

set showmatch     " set show matching parenthesis
set ignorecase    " ignore case when searching
set smartcase     " ignore case if search pattern is all lowercase,
                  "    case-sensitive otherwise
set hlsearch      " highlight search terms
set incsearch     " show search matches as you type

set wildignore=*.swp,*.bak,*.pyc,*.class

set nobackup
set noswapfile

set history=150		" keep 50 lines of command line history

set pastetoggle=<F2>  " when in insert mode, ready to paste, if you press <F2>, Vim will switch to paste mode, 
                      " disabling all kinds of smartness and just pasting a whole buffer of text.


" mapping for command-T plugin
nnoremap <leader>o <Esc>:CommandT<CR>
nnoremap <leader>O <Esc>:CommandTFlush<CR>
nnoremap <leader>m <Esc>:CommandTBuffer<CR>



"" ----------------------------------


" don't allow backspacing over everything in insert mode
"set backspace=

set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands


" Local config
if filereadable(".vimrc.local")
  source .vimrc.local
endif

" Use Ack instead of Grep when available
if executable("ack")
  set grepprg=ack\ -H\ --nogroup\ --nocolor
endif


" Snippets are activated by Shift+Tab
" let g:snippetsEmu_key = "<S-Tab>"

" Tab completion options
set wildmode=list:longest,list:full
set complete=.,w,t

" Window navigation
nmap <C-J> <C-W><C-J>
nmap <C-K> <C-W><C-K>


"nnoremap <Left> :echoe "Use h"<CR>
"nnoremap <Right> :echoe "Use l"<CR>
"nnoremap <Up> :echoe "Use k"<CR>
"nnoremap <Down> :echoe "Use j"<CR>






